version: '3.8'

services:
  music163bot:
    image: smhw3565/music163bot-go-2:latest
    container_name: music163bot
    restart: always
    volumes:
      - ./config.ini:/app/config.ini
      - ./log:/app/log
      - ./src:/app/src
    working_dir: /app
    depends_on:
      - telegram-bot-api
    networks:
      - bot-network

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-bot-api
    restart: always
    environment:
      TELEGRAM_API_ID: ""         # 您的 telegram_api_id
      TELEGRAM_API_HASH: ""       # 您的 telegram_api_hash
      TELEGRAM_BOT_API_MAX_FILE_SIZE: "2147483648"  # 2GB
      TELEGRAM_BOT_API_MAX_CONNECTIONS: "500"
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"
    networks:
      - bot-network

volumes:
  telegram-bot-api-data:

networks:
  bot-network: